version: '3.8'

networks:
  net-sir:
    external: true

services:
  py_client_user:
    build: './05-client-py'
    container_name: client05-py
    restart: always
    volumes:
      - "./05-client-py/src:/src"
    depends_on:
      - py_server_user
    ports:
      - "5300:5300"
  py_server_user:
    build: './04-server-py'
    container_name: server04-py
    restart: always
    volumes:
      - "./04-server-py/src:/src"
    depends_on:
      - mysql_server_user
    ports:
      - "1459:1459"
  c_client_user:
    build: './03-client-c'
    container_name: client03-c
    restart: always
    networks:
      - net-sir
    volumes:
      - "./03-client-c/src:/src"
    depends_on:
      - c_server_user
    ports:
      - "5268:5268"
  c_server_user:
    build: './02-server-c'
    container_name: server02-c
    restart: always
    networks:
      - net-sir
    volumes:
      - "./02-server-c/src:/src"
    depends_on:
      - mysql_server_user
    environment:
      - MYSQL_SERVER_IP=mysql_server_user
    ports:
      - "11235:11235"
  mysql_server_user:
    build: './01-mysql'
    container_name: server01-mysql
    restart: always
    volumes:
      - "./01-mysql/src/sir_db.sql:/docker-entrypoint-initdb.d/init_1.sql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "30000:3306"
